language: node_js
node_js:
  - "lts/*"
install:
  - npm install --global cordova-coho fairmanager/spodr#feature/install
script:
  - coho repo-update -g -r all
  - spodr install -j8 --verbose
  - cd cordova-plugin-inappbrowser
  - npm test
